### ISSUE TITLE
Why is the license Apache 2?

### ISSUE THREAD

**Issue by MattDodsonEnglish** [grafana/k6-learn#13]
I don't think the Apache 2 is suitable for our use:
- It's a code license and this is a media repo.
- A copyleft license would be more in line with the other open source repos of this this organization.

With these two things in mind, I propose [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) (SA is "sharealike," similar in concept to copyleft). If I understand the license well, anyone could copy and remix the material here, as long as they gave credit and released the remix under the same license.

Right now, under Apache 2, I think derivative works would just need to attribute and indicate changes. For a CC license that doesn't have this copyleft clause, we could use one of the non-share alikes.

**Comment by ppcano** [comment]
I am ok with the license change and 100% onboard with using the same license for other similar content projects across Grafana projects. But, IMO, this type of content/educational project is easier to manage outside the code.

Is there any other similar content project on the Grafana repos? Perhaps, this is the first case, and then it should pave the way to escalate this case to agree on the license for this type of project.
