### ISSUE TITLE
Move workshop to its own directory

### ISSUE THREAD

**Issue by MattDodsonEnglish** [grafana/k6-learn#4]
There's a lot of files to navigate in the `modules` dir. Separating them should make it easier to navigate, especially since there's no a clear distinction between "workshop" and "non-workshop" content.

This should not be hard, we just need to make sure that we properly change the file paths in all the in-text anchors and images.

**Comment by nicolevanderhoeven** [comment]
Done in [this commit](https://github.com/grafana/k6-learn/commit/dc33fefd4be8ef349bf1eee88997f3239f110139). Feel free to reorganize further if necessary!
